
ALTER TABLE public.staff
  ADD COLUMN IF NOT EXISTS date_of_birth date,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS pronouns text,
  ADD COLUMN IF NOT EXISTS sexuality text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS is_cald boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS country_of_birth text,
  ADD COLUMN IF NOT EXISTS languages_spoken text,
  ADD COLUMN IF NOT EXISTS interpreter_required boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS indigenous_status text,
  ADD COLUMN IF NOT EXISTS emergency_contact_name text,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone text,
  ADD COLUMN IF NOT EXISTS emergency_contact_relationship text,
  ADD COLUMN IF NOT EXISTS end_date date,
  ADD COLUMN IF NOT EXISTS probation_end_date date,
  ADD COLUMN IF NOT EXISTS pay_rate numeric,
  ADD COLUMN IF NOT EXISTS award_level text,
  ADD COLUMN IF NOT EXISTS tax_file_number_on_file boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS superannuation_fund text,
  ADD COLUMN IF NOT EXISTS bank_details_on_file boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS ndis_worker_id text,
  ADD COLUMN IF NOT EXISTS disability_status text,
  ADD COLUMN IF NOT EXISTS working_with_children_number text,
  ADD COLUMN IF NOT EXISTS ndis_screening_number text;
