
ALTER TABLE public.participants
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS pronouns text,
  ADD COLUMN IF NOT EXISTS sexuality text,
  ADD COLUMN IF NOT EXISTS is_cald boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS country_of_birth text,
  ADD COLUMN IF NOT EXISTS languages_spoken text,
  ADD COLUMN IF NOT EXISTS interpreter_required boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS indigenous_status text,
  ADD COLUMN IF NOT EXISTS diagnosis text,
  ADD COLUMN IF NOT EXISTS allergies_detail text,
  ADD COLUMN IF NOT EXISTS dietary_requirements text,
  ADD COLUMN IF NOT EXISTS medical_conditions text,
  ADD COLUMN IF NOT EXISTS gp_name text,
  ADD COLUMN IF NOT EXISTS gp_phone text,
  ADD COLUMN IF NOT EXISTS gp_address text,
  ADD COLUMN IF NOT EXISTS pharmacy_name text,
  ADD COLUMN IF NOT EXISTS pharmacy_phone text,
  ADD COLUMN IF NOT EXISTS hospital_preference text,
  ADD COLUMN IF NOT EXISTS medicare_number text,
  ADD COLUMN IF NOT EXISTS ambulance_cover boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS ndis_plan_start date,
  ADD COLUMN IF NOT EXISTS ndis_plan_end date,
  ADD COLUMN IF NOT EXISTS plan_manager text,
  ADD COLUMN IF NOT EXISTS plan_manager_email text,
  ADD COLUMN IF NOT EXISTS plan_manager_phone text,
  ADD COLUMN IF NOT EXISTS support_coordinator text,
  ADD COLUMN IF NOT EXISTS support_coordinator_email text,
  ADD COLUMN IF NOT EXISTS support_coordinator_phone text,
  ADD COLUMN IF NOT EXISTS funding_type text,
  ADD COLUMN IF NOT EXISTS communication_needs text,
  ADD COLUMN IF NOT EXISTS communication_aids text,
  ADD COLUMN IF NOT EXISTS decision_making text,
  ADD COLUMN IF NOT EXISTS guardian_name text,
  ADD COLUMN IF NOT EXISTS guardian_phone text,
  ADD COLUMN IF NOT EXISTS guardian_relationship text,
  ADD COLUMN IF NOT EXISTS has_guardianship_order boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS advocate_name text,
  ADD COLUMN IF NOT EXISTS advocate_phone text;
