// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjlrfcwbencujnycfmqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qbHJmY3diZW5jdWpueWNmbXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MTM5NTAsImV4cCI6MjA4OTI4OTk1MH0.Q0d3FrqFi_x1XIVN7JQavtNH7-xQ7rgnHBRLlI314c4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});